# Generated by Django 3.2.3 on 2021-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_auto_20210717_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Text', models.CharField(max_length=1000)),
                ('About_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
